#' qc-doublets-viability.r
#' 
#' 19-10-07 10:30:58
#' 
#' contributor: guangchun
#'
#' generate QC plots for cell viability(%mito genes) and potential doublets(ngene vs nreads)
#' 

##libraries
suppressMessages({library(optparse)
library(Seurat)
library(ggplot2)
library(ggpubr)
library(rjson)
library(dplyr)})
print('----QC----')
option_list = list(
    make_option(c("-d", "--data"),
                type = "character",
                default = NULL,
                help = "rds file generated by load-cellranger.r",
                metavar = 'character'),
    make_option(c("-o",'--out'),
                type = 'character',
                default = 'doublets-viability-plot.pdf',
                help = 'output file name for the plot [default = %default]',
                metavar = 'character'),
    make_option(c("-c",'--param'),
                type = 'character',
                help = 'json parameter file for plot figure size',
                metavar = 'character')
);

opt_parser = OptionParser(option_list = option_list);
opt = parse_args(opt_parser);

if(is.null(opt$data)) {
    print_help(opt_parser)
    stop("Input data must be provided", call. = F)
}

##load param
param <- fromJSON(file = opt$param)

##load data
print('loading data')
combined.data = readRDS(opt$data)
print('making plots')
gpdat = tidyr::gather(data.frame(rname = rownames(combined.data@meta.data),
                                 combined.data@meta.data),
                      key = type,
                      value = value, -rname,-orig.ident)
plot.pmito = ggplot(data = filter(gpdat,type == 'percent.mito'),
                    aes(x = orig.ident,y=value))
plot.pmito = plot.pmito + geom_boxplot(aes(color = 'pink'),outlier.shape = NA) +
    ylab('') +
    xlab('')  +
    theme(axis.text.x = element_text(angle = 40,hjust = 1, vjust = 1),
          legend.position = 'none')
plot.nF = ggplot(data = filter(gpdat,type == 'nFeature_RNA'),
                    aes(x = orig.ident,y=value))
plot.nF = plot.nF + geom_boxplot(aes(color = 'pink'),outlier.shape = NA) +
    ylab('') +
    xlab('')  +
    theme(axis.text.x = element_text(angle = 40,hjust = 1, vjust = 1),
          legend.position = 'none')
plot.nRead = ggplot(data = filter(gpdat,type == 'nCount_RNA'),
                    aes(x = orig.ident,y=value))
plot.nRead = plot.nRead + geom_boxplot(aes(color = 'pink'),outlier.shape = NA) +
    ylab('') +
    xlab('')  +
    theme(axis.text.x = element_text(angle = 40,hjust = 1, vjust = 1),
          legend.position = 'none')
plot.viability = FeatureScatter(object = combined.data,
                                feature1 = "nCount_RNA",
                                feature2 = "percent.mito")
plot.doublets = FeatureScatter(object = combined.data,
                               feature1 = "nCount_RNA",
                               feature2 = "nFeature_RNA")
gp.list = list(plot.nF,
               plot.nRead,
               plot.pmito,
               plot.viability,
               plot.doublets)
do.call(ggarrange, c(gp.list, ncol = 1, nrow = 1)) -> combined.gp
pdf(opt$out)
print(combined.gp,height = param$height,
      width = param$width)
dev.off()
print('----end----')


